// مكتبة ميمز مختارة من myinstants.com (اختارها الأدمن من صفحة «أصوات قلّدها»).
// ما تنحفظ بالمستودع: Cloudflare ينزّلها بنفسه أول مرة بعد النشر ويخزّنها بالـHub، وبعدها تنخدم من عندنا.
// slug = آخر جزء من رابط الصوت: https://www.myinstants.com/en/instant/<slug>/

export const LIBRARY_SOUNDS = [
  // ---------------- أنمي (كله)
  { slug: 'omae-wa-mou-shindeiru-nani-494', title: 'Omae wa mou shindeiru… NANI', emoji: '🎌' },
  { slug: 'zehahaha-edward-teach-laugh-86', title: 'ZEHAHAHA — ضحكة بلاك بيرد', emoji: '🏴‍☠️' },
  { slug: 'za-warudo-animes-time-stop', title: 'ZA WARUDO', emoji: '🎌' },
  { slug: 'tuturu', title: 'Tuturu', emoji: '🎌' },
  { slug: 'anime-wow', title: 'Anime Wow', emoji: '🎌' },
  { slug: 'sugoi-sugoi', title: 'Sugoi Sugoi', emoji: '🎌' },
  { slug: 'y-hbyby-lmhqq-kwnn-58094', title: 'يا حبيبي — المحقق كونان', emoji: '🕵️' },
  { slug: 'nya-cat-girl-sound-95668', title: 'Nya~', emoji: '🐱' },
  { slug: 'jutsu-activation', title: 'Jutsu Activation', emoji: '🍥' },
  { slug: 'sukunas-ryoiki-tenkai-86102', title: 'Ryoiki Tenkai — سوكونا', emoji: '👹' },
  { slug: 'aizen-yokoso-full-55496', title: 'Aizen — Yokoso', emoji: '🗡️' },
  { slug: 'anime-girl-senpai-94787', title: 'Senpai!', emoji: '🎌' },
  { slug: 'girl-uwu-43540', title: 'UwU', emoji: '🥺' },
  { slug: 'anime-ahh-73606', title: 'Anime ahh', emoji: '🔞' },
  { slug: 'ara-ara', title: 'Ara Ara', emoji: '🔞' },
  { slug: 'ara-ara-sayonara-92340', title: 'Ara Ara Sayonara', emoji: '🔞' },
  { slug: 'happy-onichan-2654', title: 'Onii-chan', emoji: '🔞' },

  // ---------------- أنمي: جمل مشهورة (v1.5) — تنزل لوحدها بعد النشر
  // ون بيس
  { slug: 'gomu-gomu-no-pistol', title: 'Luffy — Gomu Gomu no Pistol!', emoji: '🏴‍☠️' },
  { slug: 'kaizoku-ou-ni-ore-wa-naru', title: 'Luffy — Kaizoku ou ni ore wa naru!', emoji: '🏴‍☠️' },
  { slug: 'luffy-laugh-good-26576', title: 'Luffy — Shishishi', emoji: '🏴‍☠️' },
  { slug: 'roronoa-zoro-santoryu-18360', title: 'Zoro — Santoryu Onigiri!', emoji: '🏴‍☠️' },
  { slug: 'nami-san-45137', title: 'Sanji — Nami-swaaan!', emoji: '🏴‍☠️' },
  { slug: 'franky-supeeer-57310', title: 'Franky — SUPEEER!', emoji: '🏴‍☠️' },
  { slug: 'the-one-piece-is-real-98167', title: 'Whitebeard — The One Piece is real!', emoji: '🏴‍☠️' },
  { slug: 'kaido-laugh-57771', title: 'Kaido — Wororo', emoji: '🏴‍☠️' },
  // ناروتو
  { slug: 'dattebayo-naruto-6237', title: 'Naruto — Dattebayo!', emoji: '🍥' },
  { slug: 'naruto-rasengan-shippuden-23365', title: 'Naruto — Rasengan!', emoji: '🍥' },
  { slug: 'kage-bunshin-no-jutsu-naruto-21667', title: 'Naruto — Kage Bunshin no Jutsu!', emoji: '🍥' },
  { slug: 'sasukeeee-33193', title: 'Naruto — SASUKEEE!', emoji: '🍥' },
  { slug: 'mangekyo-sharingan', title: 'Mangekyo Sharingan', emoji: '🍥' },
  { slug: 'amaterasu', title: 'Amaterasu', emoji: '🍥' },
  { slug: 'pain-itami-o-kanjiro-15457', title: 'Pain — Shinra Tensei!', emoji: '🍥' },
  { slug: 'katon-gouka-mekkyaku-94634', title: 'Madara — Katon: Goka Mekkyaku!', emoji: '🍥' },
  { slug: 'kakashi-raikiri-84986', title: 'Kakashi — Raikiri!', emoji: '🍥' },
  // بليتش
  { slug: 'ichigo-bankai-11188', title: 'Ichigo — Bankai!', emoji: '🗡️' },
  { slug: 'getsuga-tenshooouuuuu', title: 'Ichigo — Getsuga Tenshooo!', emoji: '🗡️' },
  { slug: 'bankai-byakuya', title: 'Byakuya — Senbonzakura Kageyoshi', emoji: '🗡️' },
  { slug: 'psycho-bleach-hollow-ichigo', title: 'Hollow Ichigo — Hahaha!', emoji: '🗡️' },
  // بلاك كلوفر
  { slug: 'asta-black-clover-96668', title: 'Asta — Mada mada!', emoji: '🍀' },
  // دراغون بول
  { slug: 'kamehameha', title: 'Goku — Kamehameha!', emoji: '🐉' },
  { slug: 'over-9000', title: "Vegeta — It's over 9000!", emoji: '🐉' },
  { slug: 'vegeta-final-flash', title: 'Vegeta — Final Flash!', emoji: '🐉' },
  { slug: 'frieza-ohohohohoh-46566', title: 'Frieza — Ohohoho', emoji: '🐉' },
  // جوجو
  { slug: 'yare-yare-daze-jotaro-kujo-444', title: 'Jotaro — Yare yare daze', emoji: '🕺' },
  { slug: 'jotaro-kujo-ora-ora-ora-jojo', title: 'Jotaro — ORA ORA ORA!', emoji: '🕺' },
  { slug: 'muda-muda-muda-muda-muda-muda-48281', title: 'DIO — MUDA MUDA MUDA!', emoji: '🕺' },
  { slug: 'kono-dio-da', title: 'DIO — Kono Dio da!', emoji: '🕺' },
  // هجوم العمالقة
  { slug: 'tatakae-eren-9985', title: 'Eren — Tatakae!', emoji: '⚔️' },
  { slug: 'levi-scream-kenny-51396', title: 'Levi — KENNY!', emoji: '⚔️' },
  { slug: 'eren-titan-roar-4089', title: 'Eren — Titan roar', emoji: '⚔️' },
  // قاتل الشياطين
  { slug: 'zenitsu-lightning-breath-54616', title: 'Zenitsu — Hekireki Issen', emoji: '🔥' },
  { slug: 'rengoku-umai-73805', title: 'Rengoku — Umai!', emoji: '🔥' },
  { slug: 'inosuke-laugh-89636', title: 'Inosuke — Gahaha!', emoji: '🔥' },
  // جوجوتسو كايسن
  { slug: 'gojo-domain-expansion-60533', title: 'Gojo — Ryoiki Tenkai: Muryokusho', emoji: '🤞' },
  { slug: 'nah-id-win-96219', title: "Gojo — Nah, I'd win", emoji: '🤞' },
  { slug: 'jujutsu-kaisen-besto-friendo-81988', title: 'Todo — Besto friendo!', emoji: '🤞' },
  // ديث نوت
  { slug: 'keikaku-doori', title: 'Light — Keikaku doori', emoji: '📓' },
  { slug: 'death-note-kiras-laugh-26964', title: 'Kira — Hahaha!', emoji: '📓' },
  // بوكيمون، ون بنش، هيرو أكاديميا، سباي فاميلي
  { slug: 'pika-pika', title: 'Pikachu — Pika pika!', emoji: '⚡' },
  { slug: 'saitama-ok-62742', title: 'Saitama — OK.', emoji: '👊' },
  { slug: 'saitama-serious-punch-49697', title: 'Saitama — Serious Punch!', emoji: '👊' },
  { slug: 'all-might-plus-ultra', title: 'All Might — Plus Ultra!', emoji: '💥' },
  { slug: 'deku-smash-93369', title: 'Deku — Smash!', emoji: '💥' },
  { slug: 'sxf-anya-waku-waku-27649', title: 'Anya — Waku waku!', emoji: '🥜' },

  // ---------------- باب الحارة (v1.6)
  { slug: 'bab-al-hara-ahhh-38727', title: 'آآآه — باب الحارة', emoji: '😩' },
  { slug: 'bb-lhr-sm-52997', title: 'عصام! — باب الحارة', emoji: '🏘️' },
  { slug: 'ahleen-nems-91731', title: 'أهلين نمس — باب الحارة', emoji: '🤗' },
  { slug: 'bw-htm-lshmy-48411', title: 'أبو حاتم — باب الحارة', emoji: '☕' },

  // ---------------- مسلسلات وأفلام وميمز عربية (v1.6)
  { slug: 'y-m-gwr-smyr-bw-lnyl-10278', title: 'يا عم غور — سمير أبو النيل', emoji: '🙄' },
  { slug: 'fylm-lkyf-n-msh-mrth-y-jml-96114', title: 'أنا مش مرتاح يا جمال — فيلم الكيف', emoji: '😟' },
  { slug: 'qlby-hyqf-ktkwt-28597', title: 'قلبي هيقف — كتكوت', emoji: '💓' },
  { slug: 'ylhwy-ly-y-bt-w-ly-lly-hwly-ly-rby-32231', title: 'يلهوي عليا يا بت — علي ربيع', emoji: '😵' },
  { slug: 'tl-t-zkry-nhrk-khyr-92327', title: 'نهارك خير — طلعت زكريا', emoji: '☀️' },
  { slug: 'llh-yhyyk-3436', title: 'الله يحييك — طاش ما طاش', emoji: '🤝' },
  { slug: 'wn-m-bhlk-66647', title: 'ونعم بحالك — طاش ما طاش', emoji: '🙏' },
  { slug: 'sbhnh-bhjt-sbr-39797', title: 'سبحانه! — بهجت صابر', emoji: '💪' },
  { slug: 'bhjt-sbrdhkh-92706', title: 'ضحكة بهجت صابر', emoji: '😂' },
  { slug: 'bhjt-sbr-hl-ms-23108', title: 'أحلى مسا — بهجت صابر', emoji: '🌙' },
  { slug: 'nt-yz-tbwz-khlqy-74598', title: 'إنت عايز تبوظ أخلاقي؟', emoji: '😇' },
  { slug: 'yz-trwh-lmm-91457', title: 'عايز تروح لماما؟', emoji: '🍼' },
  { slug: 'mt-ytsh-42933', title: 'متعيطش!', emoji: '😢' },
  { slug: 'n-rjl-bt-khdr-w-fkh-3225', title: 'أنا راجل بتاع خضار وفاكهة', emoji: '🍅' },
  { slug: 'y-y-m-lshgln-dy-btlnh-95348', title: 'إي يا عم، الشغلانة دي بطّلناها', emoji: '🙅‍♂️' },
  { slug: 'yh-lqrf-dh-y-jd-n-87207', title: 'إيه القرف ده يا جدعان!', emoji: '🤢' },
  { slug: 'nt-mnyn-nt-mn-frns-57035', title: 'إنت منين؟ إنت من فرنسا؟', emoji: '🥖' },
  { slug: 'mtjbsh-syr-mm-74987', title: 'متجبش سيرة ماما!', emoji: '🙊' },
  { slug: 'n-yz-nm-30768', title: 'أنا عايز أنام', emoji: '😴' },
  { slug: 'sdqny-lw-rf-61373', title: 'صدقني لو أعرف', emoji: '🤷' },
  { slug: 'lhqwn-bjd-73054', title: 'الحقونا بجد!', emoji: '🆘' },
  { slug: 'dmrtny-34529', title: 'دمّرتني!', emoji: '💔' },
  { slug: 'htdf-23604', title: 'هتدفع!', emoji: '💵' },
  { slug: 'nt-wllh-dmk-tqyl-16365', title: 'إنت والله دمك تقيل', emoji: '😒' },
  { slug: 'y-yny-lyk-nt-msh-fhm-y-hj-22957', title: 'يا عيني عليك، إنت مش فاهم أي حاجة', emoji: '🤦' },
  { slug: 'ljyr-brfw-10832', title: 'برافو! — الجيار', emoji: '👏' },
  { slug: 'y-mrw-dyb-y-khww-70750', title: 'يا عمرو دياب يا خوو!', emoji: '🎤' },
  { slug: 'lsh-bnskhn-60102', title: 'لسه بنسخّن', emoji: '♨️' },
  { slug: 'lml-b-wl-57600', title: 'الملعب ولّع!', emoji: '🏟️' },
  { slug: 'y-bn-ll-ybh-41887', title: 'يا ابن اللعيبة!', emoji: '🦶' },
  { slug: 'hy-zrybh-y-hbyby-24579', title: 'هي زريبة يا حبيبي؟', emoji: '🐄' },
  { slug: 'brhym-rhmny-15699', title: 'إبراهيم ارحمني', emoji: '😭' },
  { slug: 'lysh-yrby-lysh-91624', title: 'ليش يا ربي ليش؟', emoji: '😫' },
  { slug: 'hbyby-wl-shy-10070', title: 'حبيبي ولا شي', emoji: '😌' },
  { slug: 'hl-blkhmys-14126', title: 'هلا بالخميس!', emoji: '🎉' },
  { slug: 'bw-mrsl-ydhk-85614', title: 'ضحكة أبو مرسال', emoji: '🤣' },
  { slug: 'lk-hy-34607', title: 'لك هاي! — أبو ليلى', emoji: '😲' },
  { slug: 'y-wdy-721', title: 'يا وديع!', emoji: '📣' },
  { slug: 'wyn-lkyt-hy-lklwt-53031', title: 'وين لكيت هاي الكلاوات؟', emoji: '🧐' },
  { slug: 'wlkhdm-lkhdm-7658', title: 'والخدمة الخدمة', emoji: '💼' },
  { slug: 'mlk-mkhlw-61909', title: 'مالك مخلوع؟', emoji: '😨' },
  { slug: 'lsh-mqrytysh-37679', title: 'علاش ماقريتيش؟', emoji: '📚' },
  { slug: 'merhba-biiiik-45944', title: 'مرحبا بيك', emoji: '🌹' },
  { slug: 'hdh-mlw-hdh-4374', title: 'هذا مالو هذا؟', emoji: '❓' },

  // ---------------- أفلام ومسلسلات أجنبية (v1.6)
  { slug: 'i-am-the-danger', title: 'Heisenberg — I am the danger', emoji: '🧪' },
  { slug: 'say-my-name-breaking-bad-74216', title: 'Heisenberg — Say my name', emoji: '🎩' },
  { slug: 'terminator-ill-be-back-74922', title: "Terminator — I'll be back", emoji: '🤖' },
  { slug: 'hasta-la-vista-baby', title: 'Terminator — Hasta la vista, baby', emoji: '🕶️' },
  { slug: 'say-hello-to-my-little-friend', title: 'Tony Montana — Say hello to my little friend', emoji: '💥' },
  { slug: 'why-so-serious-joker', title: 'Joker — Why so serious?', emoji: '🃏' },
  { slug: 'you-shall-not-pass', title: 'Gandalf — You shall not pass!', emoji: '🧙' },
  { slug: 'gollum-my-precious', title: 'Gollum — My precious', emoji: '💍' },
  { slug: 'heres-johnny', title: "Jack — Here's Johnny!", emoji: '👀' },
  { slug: 'im-batman', title: "Batman — I'm Batman", emoji: '🦇' },
  { slug: 'i-am-iron-man-23526', title: 'Tony Stark — I am Iron Man', emoji: '🦾' },
  { slug: 'endgame-avengers-assemble-56256', title: 'Captain America — Avengers assemble', emoji: '🛡️' },
  { slug: 'i-am-groot', title: 'Groot — I am Groot', emoji: '🌳' },
  { slug: 'wakanda-forever-68388', title: 'Black Panther — Wakanda forever', emoji: '🐾' },
  { slug: 'i-am-inevitable-thanos-9349', title: 'Thanos — I am inevitable', emoji: '🧤' },
  { slug: 'this-is-sparta', title: 'Leonidas — This is Sparta!', emoji: '⚔️' },
  { slug: 'houston-we-have-a-problem', title: 'Houston, we have a problem', emoji: '🛰️' },
  { slug: 'may-the-force-52979', title: 'Star Wars — May the Force be with you', emoji: '✨' },
  { slug: 'i-am-your-father', title: 'Darth Vader — I am your father', emoji: '🖤' },
  { slug: 'darth-vaders-nooooo-but-without-music-99491', title: 'Darth Vader — Nooooo!', emoji: '😱' },
  { slug: 'hello-there-obi-wan-39670', title: 'Obi-Wan — Hello there', emoji: '👋' },
  { slug: 'obi-wan-has-the-high-ground', title: 'Obi-Wan — I have the high ground', emoji: '⛰️' },
  { slug: 'its-a-trap-admiral-akbar', title: "Ackbar — It's a trap!", emoji: '🐟' },
  { slug: 'to-infinity-and-beyond', title: 'Buzz Lightyear — To infinity and beyond!', emoji: '🧑‍🚀' },
  { slug: 'just-keep-swimming', title: 'Dory — Just keep swimming', emoji: '🐠' },
  { slug: 'run-forrest-run-50857', title: 'Run, Forrest, run!', emoji: '🏃' },
  { slug: 'life-is-like-a-box-of-chocolates-23193', title: 'Forrest Gump — Life is like a box of chocolates', emoji: '🍫' },
  { slug: 'bond-james-bond-79915', title: 'Bond. James Bond', emoji: '🍸' },
  { slug: 'show-me-the-money-81568', title: 'Jerry Maguire — Show me the money!', emoji: '💰' },
  { slug: 'you-cant-handle-the-truth', title: "You can't handle the truth!", emoji: '⚖️' },
  { slug: 'i-see-dead-people', title: 'I see dead people', emoji: '👻' },
  { slug: 'yippee-ki-yay-mr-falcon', title: 'John McClane — Yippee-ki-yay', emoji: '🤠' },
  { slug: 'its-alive-1328', title: "Frankenstein — It's alive!", emoji: '⚡' },
  { slug: 'winter-is-coming', title: 'Ned Stark — Winter is coming', emoji: '❄️' },
  { slug: 'you-know-nothing-jon-snow', title: 'You know nothing, Jon Snow', emoji: '🐺' },
  { slug: 'hodor', title: 'Hodor!', emoji: '🚪' },
  { slug: 'joeys-how-you-doin', title: "Joey — How you doin'?", emoji: '😏' },
  { slug: 'friends-we-were-on-a-break', title: 'Ross — We were on a break!', emoji: '⏸️' },
  { slug: 'janice-omg', title: 'Janice — Oh. My. God.', emoji: '😮' },
  { slug: 'bazinga', title: 'Sheldon — Bazinga!', emoji: '🤓' },
  { slug: 'legendary-barney-stinson-90016', title: 'Barney — Legen… dary!', emoji: '🤵' },
  { slug: 'dobby-is-free-75835', title: 'Dobby is free!', emoji: '🧦' },
  { slug: 'wingardium-leviosa', title: 'Wingardium Leviosa', emoji: '🪄' },
  { slug: 'im-the-king-of-the-world', title: "Jack — I'm the king of the world!", emoji: '🚢' },
  { slug: 'et-phone-home-88634', title: 'E.T. phone home', emoji: '👽' },
  { slug: 'clint-eastwood-make-my-day-283', title: 'Go ahead, make my day', emoji: '😎' },
  { slug: 'wilhelm-scream', title: 'Wilhelm scream', emoji: '🎬' },
  { slug: 'inconceivable', title: 'Vizzini — Inconceivable!', emoji: '🤯' },
  { slug: 'freedom-braveheart', title: 'Braveheart — Freedom!', emoji: '🏴' },
  { slug: 'you-talking-to-me-13253', title: 'Taxi Driver — You talking to me?', emoji: '🚕' },
  { slug: 'release-the-kraken', title: 'Zeus — Release the Kraken!', emoji: '🐙' },
  { slug: 'what-you-talking-about-willis-', title: "Arnold — Whatchu talkin' 'bout, Willis?", emoji: '🤨' },

  // ---------------- ألعاب وكارتون (v1.6)
  { slug: 'spongebob-im-ready-short-75952', title: "SpongeBob — I'm ready!", emoji: '🧽' },
  { slug: 'no-this-is-patrick', title: 'Patrick — No, this is Patrick!', emoji: '⭐' },
  { slug: 'homer-doh', title: "Homer — D'oh!", emoji: '🍩' },
  { slug: 'bart-ay-caramba-2514', title: 'Bart — Ay caramba!', emoji: '🛹' },
  { slug: 'shut-up-and-take-my-money-fry', title: 'Fry — Shut up and take my money!', emoji: '💸' },
  { slug: 'mario-yahoo', title: 'Mario — Yahoo!', emoji: '🍄' },
  { slug: 'its-a-me-mario', title: "Mario — It's-a me, Mario!", emoji: '🎮' },
  { slug: 'mamma-mia-mario-63554', title: 'Mario — Mamma mia!', emoji: '🍝' },
  { slug: 'gotta-go-fast', title: 'Sonic — Gotta go fast!', emoji: '🦔' },
  { slug: 'emergency-meeting-33041', title: 'Among Us — Emergency meeting!', emoji: '🚨' },
  { slug: 'villagerhmm-81873', title: 'Minecraft — Villager hmm', emoji: '⛏️' },
  { slug: 'gta-v-wasted', title: 'GTA — Wasted', emoji: '💀' },
  { slug: 'finish-him', title: 'Mortal Kombat — Finish him!', emoji: '🥊' },
  { slug: 'hadouken', title: 'Ryu — Hadouken!', emoji: '🔥' },
  { slug: 'skyrim-fus-ro-dah-short-25320', title: 'Skyrim — Fus Ro Dah!', emoji: '🐉' },
  { slug: 'leeroy-jenkins', title: 'Leeroy Jenkins!', emoji: '📢' },
  { slug: 'phoenix-wright-objection', title: 'Phoenix Wright — Objection!', emoji: '👉' },
  { slug: 'winner-winner-chicken-dinner-9', title: 'Winner winner chicken dinner', emoji: '🍗' },
  { slug: 'tom-and-jerry-scream-71256', title: 'Tom & Jerry — صرخة توم', emoji: '🐱' },
  { slug: 'scooby-doo-laugh-57069', title: 'Scooby-Doo — ضحكة', emoji: '🐶' },
  { slug: 'goofy-holler-1-25011', title: 'Goofy — صرخة', emoji: '🎿' },
  { slug: 'woody-woodpecker-laugh', title: 'Woody Woodpecker — ضحكة', emoji: '🐦' },
  { slug: 'yabba-dabba-doo', title: 'Fred Flintstone — Yabba dabba doo!', emoji: '🦴' },
  { slug: 'whats-up-doc-bugs-bunny', title: "Bugs Bunny — What's up, doc?", emoji: '🥕' },
  { slug: 'noot-noot-pingu-85062', title: 'Pingu — Noot noot!', emoji: '🐧' },
  { slug: 'ronaldo-siuuuu-24695', title: 'Ronaldo — SIUUU!', emoji: '⚽' },
  { slug: 'goal-goal-goal-goal-gooooaaaaalllllll-87125', title: 'GOOOAL!', emoji: '🥅' },

  // ---------------- عربي عام
  { slug: 'qbhk-llh-wqbh-m-jyt-bh-83', title: 'قبحك الله، وقبح ما جئت به', emoji: '🎭' },
  { slug: 'wlk-y-hqwwd-84976', title: 'ولك يا حقوود', emoji: '😤' },
  { slug: 'wlk-lw-33316', title: 'ولك الو', emoji: '📞' },
  { slug: 'ly-tl-b-wlk-lysh-78198', title: 'علي تلعب ولك ليش', emoji: '🎮' },
  { slug: 'my-y-syd-79598', title: 'عمي يا صياد', emoji: '🦅' },
  { slug: 'y-ly-rmy-lqnbl-23612', title: 'يا علي ارمي القنبلة', emoji: '💣' },
  { slug: 'llh-kbr-lyk-53488', title: 'الله أكبر عليك', emoji: '😮' },

  // ---------------- عراقي
  { slug: 'hy-shbyk-ym-wd-22997', title: 'هاي شبيك يمعود', emoji: '🇮🇶' },
  { slug: 'shnw-hdh-94992', title: 'شنو هذا', emoji: '🇮🇶' },
  { slug: 'hdrtk-mty-57659', title: 'حضرتك مطي؟', emoji: '🫏' },
  { slug: 'tl-b-bwbjy-1-46600', title: 'تلعب ببجي', emoji: '🎮' },
  { slug: 'hayaman-chu-haeymn-4611', title: 'Hayaman Chu — حەیامان', emoji: '🎶' },
  { slug: 'baxwa-xosha-awa-chya-baekhw-khoeshae-27126', title: 'بەخوا خۆشە', emoji: '🎶' },

  // ---------------- خليجي
  { slug: 'lzmyly-n-fkhwr-ny-s-wdy-61535', title: 'انا فخور اني سعودي', emoji: '🇸🇦' },
  { slug: 'wld-wshbk-nt-bdl-zyz-lshhry-13754', title: 'ولد وشبك انت', emoji: '🇸🇦' },
  { slug: 'bw-byr-y-mjnwn-32719', title: 'ابو عبير يا مجنون', emoji: '🤪' },
  { slug: 'gnty-sbhj-llh-blkhyr-50553', title: 'غناتي صبحج الله بالخير', emoji: '☀️' },
  { slug: 'l-l-shykhn-l-36970', title: 'لا لا شيخنا لا', emoji: '🙅' },

  // ---------------- مصري
  { slug: 'smw-lykw-69305', title: 'سامو عليكو', emoji: '🇪🇬' },
  { slug: 'n-mlt-yh-78116', title: 'انا عملت ايه', emoji: '🇪🇬' },
  { slug: 'ym-61939', title: 'ياماااااااا', emoji: '😱' },
  { slug: 'y-hmsss-21522', title: 'يااا حمصصص', emoji: '🫘' },
  { slug: 'kln-ndn-wnt-m-ndksh-97859', title: 'كلنا عندنا وانت معندكش', emoji: '🇪🇬' },

  // ---------------- إنكليزي
  { slug: 'fahhhhhhhhhhhhhh-3525', title: 'FAHHHHHHH', emoji: '😩' },
  { slug: 'tuco-get-out-30566', title: 'GET OUT!', emoji: '🚪' },
  { slug: 'emotional-damage-steven-he-18512', title: 'EMOTIONAL DAMAGE', emoji: '💔' },
  { slug: 'bruh', title: 'Bruh', emoji: '😐' },
  { slug: 'oh-no-no-no-laugh-56694', title: 'Oh no no no', emoji: '🙈' },
  { slug: 'michael-jackson-hee-hee-40277', title: 'Hee Hee — مايكل جاكسون', emoji: '🕺' },
  { slug: 'spiderman-meme-song-37638', title: 'أغنية سبايدرمان', emoji: '🕷️' },
  { slug: 'sad-violin-the-meme-one', title: 'الكمان الحزين', emoji: '🎻' },
  { slug: 'dun-dun-dunnnnnnnn-68584', title: 'Dun dun dunnn', emoji: '😨' },
  { slug: 'spongebob-fail-11236', title: 'سبونج بوب — فشل', emoji: '🧽' },
  { slug: 'apple-pay-45496', title: 'Apple Pay', emoji: '💳' },
  { slug: 'chicken-on-tree-screaming-53890', title: 'دجاجة تصيح', emoji: '🐔' },
  { slug: 'cat-laugh-meme-1-15761', title: 'بزونة تضحك', emoji: '😹' },
  { slug: 'm-e-o-w-82698', title: 'Meow~', emoji: '🐈' },
  { slug: 'rizz-sound-effect-54189', title: 'Rizz', emoji: '😏' },
  { slug: 'vine-boom-sound-70972', title: 'Vine Boom', emoji: '💥' },

  // ---------------- ضرطات
  { slug: 'fart', title: 'ضرطة كلاسيكية', emoji: '💨' },
  { slug: 'iraqi-fart-10611', title: 'ضرطة عراقية', emoji: '💨' },

  // ---------------- فشار (بدون كفر ولا سب أهل)
  { slug: 'y-khr-shnw-hdh-18783', title: 'يا خرا شنو هذا', emoji: '🔞' },
  { slug: 'zyj-rqy-syl-74842', title: 'زيج عراقي اصيل', emoji: '🔞' },
  { slug: 'rb-zyj-84925', title: 'راب زيج', emoji: '🔞' },
  { slug: 'shnw-kwd-ny-hn-63021', title: 'شنو كواد اني هنا', emoji: '🔞' },
  { slug: 'bdny-tshshshsh-42769', title: 'بضاني طشششش', emoji: '🔞' },
  { slug: 'bdn-ly-bhjt-sbr-64433', title: 'ابضن عليا — بهجت صابر', emoji: '🔞' },
  { slug: 'ntyl-lmhl-65366', title: 'عنتيل المحلة', emoji: '🔞' },
  { slug: 'wzyn-n-mlk-bny-dm-y-klb-11711', title: 'عاوزين نعملك بني ادم يا كلب', emoji: '🔞' },
];

export const LIBRARY_BY_SLUG = new Map(LIBRARY_SOUNDS.map((s) => [s.slug, s]));
